def configure(conf):
    pass

def build(bld):
    bld.program(
        source = 'test.cpp',
        target = 'test',
        use = ['world'],
        includes = ['../src', '/Users/danielgalvez/Desktop/Fall2015/research/vcc2016/code/WORLD/build/src/'])
