environment:
  matrix:
    - PYTHON: "C:/Python27"

init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"

skip_commits:
# Add [av skip] to commit messages for docfixes, etc to reduce load on queue
  message: /\[av skip\]/

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

build_script:
  - C:\MinGW\msys\1.0\bin\sh --login -c "
      echo 'C:\MinGW\ /MinGW' > /etc/fstab;
      cd /c/projects/world;
      ./waf configure;
      ./waf
      "
